/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        jakarta: ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
      },
      colors: {
        warm: {
          surface: '#faf9f6',
          'surface-dim': '#dbdad7',
          'surface-bright': '#faf9f6',
          'surface-container-lowest': '#ffffff',
          'surface-container-low': '#f4f3f1',
          'surface-container': '#efeeeb',
          'surface-container-high': '#e9e8e5',
          'surface-container-highest': '#e3e2e0',
          'on-surface': '#1a1c1a',
          'on-surface-variant': '#4d4636',
          'inverse-surface': '#2f312f',
          'inverse-on-surface': '#f1f1ee',
          outline: '#7f7664',
          'outline-variant': '#d1c5b0',
          'surface-tint': '#765b00',
          primary: '#765b00',
          'on-primary': '#ffffff',
          'primary-container': '#ffd464',
          'on-primary-container': '#765b00',
          'inverse-primary': '#ebc254',
          secondary: '#5f5e5e',
          'on-secondary': '#ffffff',
          'secondary-container': '#e2dfde',
          'on-secondary-container': '#636262',
          tertiary: '#5f5f56',
          'on-tertiary': '#ffffff',
          'tertiary-container': '#dcd9ce',
          'on-tertiary-container': '#605f56',
          error: '#ba1a1a',
          'on-error': '#ffffff',
          'error-container': '#ffdad6',
          'on-error-container': '#93000a',
          'primary-fixed': '#ffdf94',
          'primary-fixed-dim': '#ebc254',
          'on-primary-fixed': '#241a00',
          'on-primary-fixed-variant': '#594400',
          'secondary-fixed': '#e5e2e1',
          'secondary-fixed-dim': '#c8c6c5',
          'on-secondary-fixed': '#1b1c1c',
          'on-secondary-fixed-variant': '#474746',
          'tertiary-fixed': '#e5e2d8',
          'tertiary-fixed-dim': '#c9c7bc',
          'on-tertiary-fixed': '#1c1c15',
          'on-tertiary-fixed-variant': '#48473f',
          background: '#faf9f6',
          'on-background': '#1a1c1a',
          'surface-variant': '#e3e2e0',
        },
      },
    },
  },
  plugins: [],
}
