/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        jakarta: ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
      },
      colors: {
        warm: {
          surface: '#F8FAFC',
          'surface-dim': '#E5EDF5',
          'surface-bright': '#F8FAFC',
          'surface-container-lowest': '#ffffff',
          'surface-container-low': '#EEF3F8',
          'surface-container': '#E5EDF5',
          'surface-container-high': '#DDE7F1',
          'surface-container-highest': '#D5E1ED',
          'on-surface': '#1a1c1a',
          'on-surface-variant': '#334155',
          'inverse-surface': '#0B1220',
          'inverse-on-surface': '#F8FAFC',
          outline: '#64748B',
          'outline-variant': '#C8D6E5',
          'surface-tint': '#1E3A5F',
          primary: '#1E3A5F',
          'on-primary': '#ffffff',
          'primary-container': '#DCEBFA',
          'on-primary-container': '#1E3A5F',
          'inverse-primary': '#BFD7EF',
          secondary: '#334155',
          'on-secondary': '#ffffff',
          'secondary-container': '#EEF3F8',
          'on-secondary-container': '#334155',
          tertiary: '#64748B',
          'on-tertiary': '#ffffff',
          'tertiary-container': '#E5EDF5',
          'on-tertiary-container': '#334155',
          error: '#ba1a1a',
          'on-error': '#ffffff',
          'error-container': '#ffdad6',
          'on-error-container': '#93000a',
          'primary-fixed': '#DCEBFA',
          'primary-fixed-dim': '#BFD7EF',
          'on-primary-fixed': '#0B1220',
          'on-primary-fixed-variant': '#172D49',
          'secondary-fixed': '#EEF3F8',
          'secondary-fixed-dim': '#C8D6E5',
          'on-secondary-fixed': '#0B1220',
          'on-secondary-fixed-variant': '#334155',
          'tertiary-fixed': '#E5EDF5',
          'tertiary-fixed-dim': '#C8D6E5',
          'on-tertiary-fixed': '#0B1220',
          'on-tertiary-fixed-variant': '#334155',
          background: '#F8FAFC',
          'on-background': '#1a1c1a',
          'surface-variant': '#D5E1ED',
        },
      },
    },
  },
  plugins: [],
}
